use QLVatTu
go
--Cau 47
  CREATE TRIGGER TG_XUAT_XOA
  ON PXUAT
  INSTEAD OF DELETE
  AS
  BEGIN
  DECLARE @SOPX CHAR(4),@NGAYXUAT DATETIME
  SELECT @SOPX=SOPX FROM deleted
  SET @NGAYXUAT=(SELECT NgayXuat FROM PXUAT WHERE SOPX=@SOPX)
  --KIEM TRA
  IF CONVERT (CHAR(6),@NGAYXUAT,112)<(SELECT MAX(NAMTHANG) FROM TONKHO)
  BEGIN
  PRINT 'PHIEU XUAT CU, KHONG DUOC XOA'
  RETURN
  END
  --VIET LENH DELETE
  DELETE FROM CTPXUAT WHERE SoPX=@SOPX
  DELETE FROM PXUAT WHERE SoPX=@SOPX
  END
  --48
  DROP TRIGGER TG_PNHAP_XOA
  create trigger tg_PNHAP_Xoa on PNHAP instead of delete
as
	declare @sopn char(4), @ngaynhap datetime
	select @sopn = sopn,@ngaynhap = ngaynhap  from deleted
	if exists (select * from TONKHO where namthang = CONVERT(char(6),@ngaynhap,112))
		begin
			print 'thang nam co trong ton kho'
			return
		end
	delete from CTPNHAP where sopn=@sopn
	delete from PNHAP where sopn=@sopn
  --49
  CREATE TRIGGER TG_NHAP_XOA
  ON PNHAP
  INSTEAD OF UPDATE
  AS
  BEGIN
  DECLARE @NGAYNHAPMOI DATETIME, @NGAYDH DATETIME,@SOPN CHAR(4),@SODH CHAR(4)
  IF UPDATE(SOPN) OR UPDATE (SODH)
  BEGIN
  PRINT 'KHONG DUOC SUA SODH VA SOPN'
  RETURN 
  END
  --KIEM TRA 
  SELECT @NGAYNHAPMOI=NGAYNHAP,@SODH=SODH FROM inserted
  SELECT @NGAYDH=NGAYDH FROM DONDH WHERE SODH=@SODH
  IF @NGAYNHAPMOI<@NGAYDH
  BEGIN
  PRINT 'NGAY NHAP PHAI SAU NGAY DAT'
  RETURN
  END
  --VIET
  SELECT @SOPN=SOPN FROM inserted
  UPDATE PNHAP
  SET NgayNhap=@NGAYNHAPMOI
  WHERE SoPN=@SOPN
  END
  --CAU 50
  CREATE TRIGGER C50
  ON PXUAT
  INSTEAD OF UPDATE
  AS
  BEGIN
  --KHONG DC SAU SOPX
  IF UPDATE (SOPX)
  BEGIN
  PRINT N'KHONG SUA SO PX'
  RETURN
  END
  --KIEM TRA NAM THANG CUA NGAY XUAT MOI VA CU BANG NHAU
  DECLARE @NGAYXUATNEW DATETIME,@NGAYXUATOLD DATETIME
  SET @NGAYXUATNEW=(SELECT NGAYXUAT FROM inserted)
  SET @NGAYXUATOLD=(SELECT NGAYXUAT FROM deleted)
  IF CONVERT (CHAR(6),@NGAYXUATNEW,112)=CONVERT(CHAR(6),@NGAYXUATOLD,112)
  BEGIN
  PRINT N'NAM THANG THANG CUA NGAY XUAT MOI VA CU KHONG TRUNG NHAU'
  RETURN
  END
  --VIET LENH UPDATE
   DECLARE @TENKHACH NVARCHAR(100),@SOPX CHAR(4)
  SELECT @TENKHACH=TenHK FROM INSERTED
  SELECT @SOPX=SOPX FROM inserted
  UPDATE PXUAT
  SET NgayXuat=@NGAYXUATNEW,TenHK=@TENKHACH
  WHERE SoPX=@SOPX
  END
  --THU NGHIEM
  SELECT * FROM PXUAT
  UPDATE PXUAT
  SET NgayXuat='12/01/2002',TenHK='DEF'
  WHERE SoPX='X000'
